/* 
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use std::rc::Rc;
use std::borrow::Borrow;
use std::borrow::Cow;
use std::collections::HashMap;

use hyper;
use serde_json;
use futures;
use futures::{Future, Stream};

use hyper::header::UserAgent;

use super::{Error, configuration};

pub struct AccountipstatApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> AccountipstatApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> AccountipstatApiClient<C> {
        AccountipstatApiClient {
            configuration: configuration,
        }
    }
}

pub trait AccountipstatApi {
    fn i_p_stat_router_get_all_aggregate_ip_stats(&self, x_account_api_key: &str, ipid: i64, from: &str, to: &str) -> Box<Future<Item = ::models::ModelsStat, Error = Error<serde_json::Value>>>;
    fn i_p_stat_router_get_all_aggregate_ip_stats_by_group(&self, x_account_api_key: &str, ipid: i64, provider: &str, from: &str, to: &str) -> Box<Future<Item = ::models::ModelsStat, Error = Error<serde_json::Value>>>;
    fn i_p_stat_router_get_all_aggregated_provider_stats_for_a_ip(&self, x_account_api_key: &str, ipid: i64, from: &str, to: &str) -> Box<Future<Item = Vec<::models::ModelsPipStat>, Error = Error<serde_json::Value>>>;
    fn i_p_stat_router_get_all_aggregated_provider_stats_for_a_specific_sub_account_of_a_ip(&self, x_account_api_key: &str, ipid: i64, sid: i64, from: &str, to: &str) -> Box<Future<Item = Vec<::models::ModelsPipStat>, Error = Error<serde_json::Value>>>;
    fn i_p_stat_router_get_all_aggregated_sub_account_stats_for_an_ip(&self, x_account_api_key: &str, ipid: i64, from: &str, to: &str) -> Box<Future<Item = Vec<::models::ModelsSipStat>, Error = Error<serde_json::Value>>>;
    fn i_p_stat_router_get_all_ip_stats(&self, x_account_api_key: &str, ipid: i64, from: &str, to: &str) -> Box<Future<Item = Vec<::models::ModelsRipStat>, Error = Error<serde_json::Value>>>;
    fn i_p_stat_router_get_all_ip_stats_by_group(&self, ipid: i64, x_account_api_key: &str, provider: &str, from: &str, to: &str) -> Box<Future<Item = Vec<::models::ModelsRipStat>, Error = Error<serde_json::Value>>>;
}


impl<C: hyper::client::Connect>AccountipstatApi for AccountipstatApiClient<C> {
    fn i_p_stat_router_get_all_aggregate_ip_stats(&self, x_account_api_key: &str, ipid: i64, from: &str, to: &str) -> Box<Future<Item = ::models::ModelsStat, Error = Error<serde_json::Value>>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query_string = {
            let mut query = ::url::form_urlencoded::Serializer::new(String::new());
            query.append_pair("from", &from.to_string());
            query.append_pair("to", &to.to_string());
            query.finish()
        };
        let uri_str = format!("{}/account/ip/stat/{ipid}/aggregate?{}", configuration.base_path, query_string, ipid=ipid);

        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut uri: hyper::Uri = uri_str.parse().unwrap();

        let mut req = hyper::Request::new(method, uri);

        if let Some(ref user_agent) = configuration.user_agent {
            req.headers_mut().set(UserAgent::new(Cow::Owned(user_agent.clone())));
        }

        {
            let mut headers = req.headers_mut();
            headers.set_raw("X-Account-ApiKey", x_account_api_key);
        }



        // send request
        Box::new(
        configuration.client.request(req)
            .map_err(|e| Error::from(e))
            .and_then(|resp| {
                let status = resp.status();
                resp.body().concat2()
                    .and_then(move |body| Ok((status, body)))
                    .map_err(|e| Error::from(e))
            })
            .and_then(|(status, body)| {
                if status.is_success() {
                    Ok(body)
                } else {
                    Err(Error::from((status, &*body)))
                }
            })
            .and_then(|body| {
                let parsed: Result<::models::ModelsStat, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            })
        )
    }

    fn i_p_stat_router_get_all_aggregate_ip_stats_by_group(&self, x_account_api_key: &str, ipid: i64, provider: &str, from: &str, to: &str) -> Box<Future<Item = ::models::ModelsStat, Error = Error<serde_json::Value>>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query_string = {
            let mut query = ::url::form_urlencoded::Serializer::new(String::new());
            query.append_pair("from", &from.to_string());
            query.append_pair("to", &to.to_string());
            query.append_pair("provider", &provider.to_string());
            query.finish()
        };
        let uri_str = format!("{}/account/ip/stat/{ipid}/aggregate/provider?{}", configuration.base_path, query_string, ipid=ipid);

        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut uri: hyper::Uri = uri_str.parse().unwrap();

        let mut req = hyper::Request::new(method, uri);

        if let Some(ref user_agent) = configuration.user_agent {
            req.headers_mut().set(UserAgent::new(Cow::Owned(user_agent.clone())));
        }

        {
            let mut headers = req.headers_mut();
            headers.set_raw("X-Account-ApiKey", x_account_api_key);
        }



        // send request
        Box::new(
        configuration.client.request(req)
            .map_err(|e| Error::from(e))
            .and_then(|resp| {
                let status = resp.status();
                resp.body().concat2()
                    .and_then(move |body| Ok((status, body)))
                    .map_err(|e| Error::from(e))
            })
            .and_then(|(status, body)| {
                if status.is_success() {
                    Ok(body)
                } else {
                    Err(Error::from((status, &*body)))
                }
            })
            .and_then(|body| {
                let parsed: Result<::models::ModelsStat, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            })
        )
    }

    fn i_p_stat_router_get_all_aggregated_provider_stats_for_a_ip(&self, x_account_api_key: &str, ipid: i64, from: &str, to: &str) -> Box<Future<Item = Vec<::models::ModelsPipStat>, Error = Error<serde_json::Value>>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query_string = {
            let mut query = ::url::form_urlencoded::Serializer::new(String::new());
            query.append_pair("from", &from.to_string());
            query.append_pair("to", &to.to_string());
            query.finish()
        };
        let uri_str = format!("{}/account/ip/stat/{ipid}/aggregate/providers?{}", configuration.base_path, query_string, ipid=ipid);

        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut uri: hyper::Uri = uri_str.parse().unwrap();

        let mut req = hyper::Request::new(method, uri);

        if let Some(ref user_agent) = configuration.user_agent {
            req.headers_mut().set(UserAgent::new(Cow::Owned(user_agent.clone())));
        }

        {
            let mut headers = req.headers_mut();
            headers.set_raw("X-Account-ApiKey", x_account_api_key);
        }



        // send request
        Box::new(
        configuration.client.request(req)
            .map_err(|e| Error::from(e))
            .and_then(|resp| {
                let status = resp.status();
                resp.body().concat2()
                    .and_then(move |body| Ok((status, body)))
                    .map_err(|e| Error::from(e))
            })
            .and_then(|(status, body)| {
                if status.is_success() {
                    Ok(body)
                } else {
                    Err(Error::from((status, &*body)))
                }
            })
            .and_then(|body| {
                let parsed: Result<Vec<::models::ModelsPipStat>, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            })
        )
    }

    fn i_p_stat_router_get_all_aggregated_provider_stats_for_a_specific_sub_account_of_a_ip(&self, x_account_api_key: &str, ipid: i64, sid: i64, from: &str, to: &str) -> Box<Future<Item = Vec<::models::ModelsPipStat>, Error = Error<serde_json::Value>>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query_string = {
            let mut query = ::url::form_urlencoded::Serializer::new(String::new());
            query.append_pair("from", &from.to_string());
            query.append_pair("to", &to.to_string());
            query.finish()
        };
        let uri_str = format!("{}/account/ip/stat/{ipid}/aggregate/sid/{sid}/providers?{}", configuration.base_path, query_string, ipid=ipid, sid=sid);

        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut uri: hyper::Uri = uri_str.parse().unwrap();

        let mut req = hyper::Request::new(method, uri);

        if let Some(ref user_agent) = configuration.user_agent {
            req.headers_mut().set(UserAgent::new(Cow::Owned(user_agent.clone())));
        }

        {
            let mut headers = req.headers_mut();
            headers.set_raw("X-Account-ApiKey", x_account_api_key);
        }



        // send request
        Box::new(
        configuration.client.request(req)
            .map_err(|e| Error::from(e))
            .and_then(|resp| {
                let status = resp.status();
                resp.body().concat2()
                    .and_then(move |body| Ok((status, body)))
                    .map_err(|e| Error::from(e))
            })
            .and_then(|(status, body)| {
                if status.is_success() {
                    Ok(body)
                } else {
                    Err(Error::from((status, &*body)))
                }
            })
            .and_then(|body| {
                let parsed: Result<Vec<::models::ModelsPipStat>, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            })
        )
    }

    fn i_p_stat_router_get_all_aggregated_sub_account_stats_for_an_ip(&self, x_account_api_key: &str, ipid: i64, from: &str, to: &str) -> Box<Future<Item = Vec<::models::ModelsSipStat>, Error = Error<serde_json::Value>>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query_string = {
            let mut query = ::url::form_urlencoded::Serializer::new(String::new());
            query.append_pair("from", &from.to_string());
            query.append_pair("to", &to.to_string());
            query.finish()
        };
        let uri_str = format!("{}/account/ip/stat/{ipid}/aggregate/subaccounts?{}", configuration.base_path, query_string, ipid=ipid);

        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut uri: hyper::Uri = uri_str.parse().unwrap();

        let mut req = hyper::Request::new(method, uri);

        if let Some(ref user_agent) = configuration.user_agent {
            req.headers_mut().set(UserAgent::new(Cow::Owned(user_agent.clone())));
        }

        {
            let mut headers = req.headers_mut();
            headers.set_raw("X-Account-ApiKey", x_account_api_key);
        }



        // send request
        Box::new(
        configuration.client.request(req)
            .map_err(|e| Error::from(e))
            .and_then(|resp| {
                let status = resp.status();
                resp.body().concat2()
                    .and_then(move |body| Ok((status, body)))
                    .map_err(|e| Error::from(e))
            })
            .and_then(|(status, body)| {
                if status.is_success() {
                    Ok(body)
                } else {
                    Err(Error::from((status, &*body)))
                }
            })
            .and_then(|body| {
                let parsed: Result<Vec<::models::ModelsSipStat>, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            })
        )
    }

    fn i_p_stat_router_get_all_ip_stats(&self, x_account_api_key: &str, ipid: i64, from: &str, to: &str) -> Box<Future<Item = Vec<::models::ModelsRipStat>, Error = Error<serde_json::Value>>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query_string = {
            let mut query = ::url::form_urlencoded::Serializer::new(String::new());
            query.append_pair("from", &from.to_string());
            query.append_pair("to", &to.to_string());
            query.finish()
        };
        let uri_str = format!("{}/account/ip/stat/{ipid}?{}", configuration.base_path, query_string, ipid=ipid);

        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut uri: hyper::Uri = uri_str.parse().unwrap();

        let mut req = hyper::Request::new(method, uri);

        if let Some(ref user_agent) = configuration.user_agent {
            req.headers_mut().set(UserAgent::new(Cow::Owned(user_agent.clone())));
        }

        {
            let mut headers = req.headers_mut();
            headers.set_raw("X-Account-ApiKey", x_account_api_key);
        }



        // send request
        Box::new(
        configuration.client.request(req)
            .map_err(|e| Error::from(e))
            .and_then(|resp| {
                let status = resp.status();
                resp.body().concat2()
                    .and_then(move |body| Ok((status, body)))
                    .map_err(|e| Error::from(e))
            })
            .and_then(|(status, body)| {
                if status.is_success() {
                    Ok(body)
                } else {
                    Err(Error::from((status, &*body)))
                }
            })
            .and_then(|body| {
                let parsed: Result<Vec<::models::ModelsRipStat>, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            })
        )
    }

    fn i_p_stat_router_get_all_ip_stats_by_group(&self, ipid: i64, x_account_api_key: &str, provider: &str, from: &str, to: &str) -> Box<Future<Item = Vec<::models::ModelsRipStat>, Error = Error<serde_json::Value>>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query_string = {
            let mut query = ::url::form_urlencoded::Serializer::new(String::new());
            query.append_pair("from", &from.to_string());
            query.append_pair("to", &to.to_string());
            query.append_pair("provider", &provider.to_string());
            query.finish()
        };
        let uri_str = format!("{}/account/ip/stat/{ipid}/provider?{}", configuration.base_path, query_string, ipid=ipid);

        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut uri: hyper::Uri = uri_str.parse().unwrap();

        let mut req = hyper::Request::new(method, uri);

        if let Some(ref user_agent) = configuration.user_agent {
            req.headers_mut().set(UserAgent::new(Cow::Owned(user_agent.clone())));
        }

        {
            let mut headers = req.headers_mut();
            headers.set_raw("X-Account-ApiKey", x_account_api_key);
        }



        // send request
        Box::new(
        configuration.client.request(req)
            .map_err(|e| Error::from(e))
            .and_then(|resp| {
                let status = resp.status();
                resp.body().concat2()
                    .and_then(move |body| Ok((status, body)))
                    .map_err(|e| Error::from(e))
            })
            .and_then(|(status, body)| {
                if status.is_success() {
                    Ok(body)
                } else {
                    Err(Error::from((status, &*body)))
                }
            })
            .and_then(|body| {
                let parsed: Result<Vec<::models::ModelsRipStat>, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            })
        )
    }

}
