/* 
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ModelsInstance {
  #[serde(rename = "created")]
  created: Option<i64>,
  #[serde(rename = "endpoint")]
  endpoint: Option<String>,
  #[serde(rename = "id")]
  id: Option<i64>,
  #[serde(rename = "ips")]
  ips: Option<Vec<::models::ModelsIp>>,
  #[serde(rename = "name")]
  name: Option<String>
}

impl ModelsInstance {
  pub fn new() -> ModelsInstance {
    ModelsInstance {
      created: None,
      endpoint: None,
      id: None,
      ips: None,
      name: None
    }
  }

  pub fn set_created(&mut self, created: i64) {
    self.created = Some(created);
  }

  pub fn with_created(mut self, created: i64) -> ModelsInstance {
    self.created = Some(created);
    self
  }

  pub fn created(&self) -> Option<&i64> {
    self.created.as_ref()
  }

  pub fn reset_created(&mut self) {
    self.created = None;
  }

  pub fn set_endpoint(&mut self, endpoint: String) {
    self.endpoint = Some(endpoint);
  }

  pub fn with_endpoint(mut self, endpoint: String) -> ModelsInstance {
    self.endpoint = Some(endpoint);
    self
  }

  pub fn endpoint(&self) -> Option<&String> {
    self.endpoint.as_ref()
  }

  pub fn reset_endpoint(&mut self) {
    self.endpoint = None;
  }

  pub fn set_id(&mut self, id: i64) {
    self.id = Some(id);
  }

  pub fn with_id(mut self, id: i64) -> ModelsInstance {
    self.id = Some(id);
    self
  }

  pub fn id(&self) -> Option<&i64> {
    self.id.as_ref()
  }

  pub fn reset_id(&mut self) {
    self.id = None;
  }

  pub fn set_ips(&mut self, ips: Vec<::models::ModelsIp>) {
    self.ips = Some(ips);
  }

  pub fn with_ips(mut self, ips: Vec<::models::ModelsIp>) -> ModelsInstance {
    self.ips = Some(ips);
    self
  }

  pub fn ips(&self) -> Option<&Vec<::models::ModelsIp>> {
    self.ips.as_ref()
  }

  pub fn reset_ips(&mut self) {
    self.ips = None;
  }

  pub fn set_name(&mut self, name: String) {
    self.name = Some(name);
  }

  pub fn with_name(mut self, name: String) -> ModelsInstance {
    self.name = Some(name);
    self
  }

  pub fn name(&self) -> Option<&String> {
    self.name.as_ref()
  }

  pub fn reset_name(&mut self) {
    self.name = None;
  }

}



