/* 
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ModelsEip {
  #[serde(rename = "publicIP")]
  public_ip: Option<String>
}

impl ModelsEip {
  pub fn new() -> ModelsEip {
    ModelsEip {
      public_ip: None
    }
  }

  pub fn set_public_ip(&mut self, public_ip: String) {
    self.public_ip = Some(public_ip);
  }

  pub fn with_public_ip(mut self, public_ip: String) -> ModelsEip {
    self.public_ip = Some(public_ip);
    self
  }

  pub fn public_ip(&self) -> Option<&String> {
    self.public_ip.as_ref()
  }

  pub fn reset_public_ip(&mut self) {
    self.public_ip = None;
  }

}



