/* 
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ModelsEmailList {
  #[serde(rename = "emailIds")]
  email_ids: Option<Value>
}

impl ModelsEmailList {
  pub fn new() -> ModelsEmailList {
    ModelsEmailList {
      email_ids: None
    }
  }

  pub fn set_email_ids(&mut self, email_ids: Value) {
    self.email_ids = Some(email_ids);
  }

  pub fn with_email_ids(mut self, email_ids: Value) -> ModelsEmailList {
    self.email_ids = Some(email_ids);
    self
  }

  pub fn email_ids(&self) -> Option<&Value> {
    self.email_ids.as_ref()
  }

  pub fn reset_email_ids(&mut self) {
    self.email_ids = None;
  }

}



