/* 
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ModelsSipStat {
  #[serde(rename = "name")]
  name: Option<String>,
  #[serde(rename = "sid")]
  sid: Option<i64>,
  #[serde(rename = "stat")]
  stat: Option<::models::ModelsIpStat>
}

impl ModelsSipStat {
  pub fn new() -> ModelsSipStat {
    ModelsSipStat {
      name: None,
      sid: None,
      stat: None
    }
  }

  pub fn set_name(&mut self, name: String) {
    self.name = Some(name);
  }

  pub fn with_name(mut self, name: String) -> ModelsSipStat {
    self.name = Some(name);
    self
  }

  pub fn name(&self) -> Option<&String> {
    self.name.as_ref()
  }

  pub fn reset_name(&mut self) {
    self.name = None;
  }

  pub fn set_sid(&mut self, sid: i64) {
    self.sid = Some(sid);
  }

  pub fn with_sid(mut self, sid: i64) -> ModelsSipStat {
    self.sid = Some(sid);
    self
  }

  pub fn sid(&self) -> Option<&i64> {
    self.sid.as_ref()
  }

  pub fn reset_sid(&mut self) {
    self.sid = None;
  }

  pub fn set_stat(&mut self, stat: ::models::ModelsIpStat) {
    self.stat = Some(stat);
  }

  pub fn with_stat(mut self, stat: ::models::ModelsIpStat) -> ModelsSipStat {
    self.stat = Some(stat);
    self
  }

  pub fn stat(&self) -> Option<&::models::ModelsIpStat> {
    self.stat.as_ref()
  }

  pub fn reset_stat(&mut self) {
    self.stat = None;
  }

}



