/* 
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ModelsEIncident {
  #[serde(rename = "author")]
  author: Option<::models::ModelsIeMember>,
  #[serde(rename = "description")]
  description: Option<String>,
  #[serde(rename = "relatedIP")]
  related_ip: Option<::models::ModelsIeip>,
  #[serde(rename = "relatedSubAccount")]
  related_sub_account: Option<::models::ModelsIeSubAccount>,
  #[serde(rename = "status")]
  status: Option<i64>,
  #[serde(rename = "summary")]
  summary: Option<String>,
  #[serde(rename = "tags")]
  tags: Option<Vec<::models::ModelsIeTag>>
}

impl ModelsEIncident {
  pub fn new() -> ModelsEIncident {
    ModelsEIncident {
      author: None,
      description: None,
      related_ip: None,
      related_sub_account: None,
      status: None,
      summary: None,
      tags: None
    }
  }

  pub fn set_author(&mut self, author: ::models::ModelsIeMember) {
    self.author = Some(author);
  }

  pub fn with_author(mut self, author: ::models::ModelsIeMember) -> ModelsEIncident {
    self.author = Some(author);
    self
  }

  pub fn author(&self) -> Option<&::models::ModelsIeMember> {
    self.author.as_ref()
  }

  pub fn reset_author(&mut self) {
    self.author = None;
  }

  pub fn set_description(&mut self, description: String) {
    self.description = Some(description);
  }

  pub fn with_description(mut self, description: String) -> ModelsEIncident {
    self.description = Some(description);
    self
  }

  pub fn description(&self) -> Option<&String> {
    self.description.as_ref()
  }

  pub fn reset_description(&mut self) {
    self.description = None;
  }

  pub fn set_related_ip(&mut self, related_ip: ::models::ModelsIeip) {
    self.related_ip = Some(related_ip);
  }

  pub fn with_related_ip(mut self, related_ip: ::models::ModelsIeip) -> ModelsEIncident {
    self.related_ip = Some(related_ip);
    self
  }

  pub fn related_ip(&self) -> Option<&::models::ModelsIeip> {
    self.related_ip.as_ref()
  }

  pub fn reset_related_ip(&mut self) {
    self.related_ip = None;
  }

  pub fn set_related_sub_account(&mut self, related_sub_account: ::models::ModelsIeSubAccount) {
    self.related_sub_account = Some(related_sub_account);
  }

  pub fn with_related_sub_account(mut self, related_sub_account: ::models::ModelsIeSubAccount) -> ModelsEIncident {
    self.related_sub_account = Some(related_sub_account);
    self
  }

  pub fn related_sub_account(&self) -> Option<&::models::ModelsIeSubAccount> {
    self.related_sub_account.as_ref()
  }

  pub fn reset_related_sub_account(&mut self) {
    self.related_sub_account = None;
  }

  pub fn set_status(&mut self, status: i64) {
    self.status = Some(status);
  }

  pub fn with_status(mut self, status: i64) -> ModelsEIncident {
    self.status = Some(status);
    self
  }

  pub fn status(&self) -> Option<&i64> {
    self.status.as_ref()
  }

  pub fn reset_status(&mut self) {
    self.status = None;
  }

  pub fn set_summary(&mut self, summary: String) {
    self.summary = Some(summary);
  }

  pub fn with_summary(mut self, summary: String) -> ModelsEIncident {
    self.summary = Some(summary);
    self
  }

  pub fn summary(&self) -> Option<&String> {
    self.summary.as_ref()
  }

  pub fn reset_summary(&mut self) {
    self.summary = None;
  }

  pub fn set_tags(&mut self, tags: Vec<::models::ModelsIeTag>) {
    self.tags = Some(tags);
  }

  pub fn with_tags(mut self, tags: Vec<::models::ModelsIeTag>) -> ModelsEIncident {
    self.tags = Some(tags);
    self
  }

  pub fn tags(&self) -> Option<&Vec<::models::ModelsIeTag>> {
    self.tags.as_ref()
  }

  pub fn reset_tags(&mut self) {
    self.tags = None;
  }

}



