/* 
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ModelsSuppressionReason {
}

impl ModelsSuppressionReason {
  pub fn new() -> ModelsSuppressionReason {
    ModelsSuppressionReason {
    }
  }

}



