/* 
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ModelsPipStat {
  #[serde(rename = "name")]
  name: Option<String>,
  #[serde(rename = "stat")]
  stat: Option<::models::ModelsIpStat>
}

impl ModelsPipStat {
  pub fn new() -> ModelsPipStat {
    ModelsPipStat {
      name: None,
      stat: None
    }
  }

  pub fn set_name(&mut self, name: String) {
    self.name = Some(name);
  }

  pub fn with_name(mut self, name: String) -> ModelsPipStat {
    self.name = Some(name);
    self
  }

  pub fn name(&self) -> Option<&String> {
    self.name.as_ref()
  }

  pub fn reset_name(&mut self) {
    self.name = None;
  }

  pub fn set_stat(&mut self, stat: ::models::ModelsIpStat) {
    self.stat = Some(stat);
  }

  pub fn with_stat(mut self, stat: ::models::ModelsIpStat) -> ModelsPipStat {
    self.stat = Some(stat);
    self
  }

  pub fn stat(&self) -> Option<&::models::ModelsIpStat> {
    self.stat.as_ref()
  }

  pub fn reset_stat(&mut self) {
    self.stat = None;
  }

}



