/* 
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ModelsDomain {
  #[serde(rename = "created")]
  created: Option<i64>,
  #[serde(rename = "dkim")]
  dkim: Option<::models::ModelsDnsRecord>,
  #[serde(rename = "dkimConfig")]
  dkim_config: Option<String>,
  #[serde(rename = "dkimVerified")]
  dkim_verified: Option<bool>,
  #[serde(rename = "id")]
  id: Option<i64>,
  #[serde(rename = "name")]
  name: Option<String>,
  #[serde(rename = "returnPath")]
  return_path: Option<::models::ModelsDnsRecord>,
  #[serde(rename = "returnPathVerified")]
  return_path_verified: Option<bool>,
  #[serde(rename = "track")]
  track: Option<::models::ModelsDnsRecord>,
  #[serde(rename = "trackVerified")]
  track_verified: Option<bool>,
  #[serde(rename = "verified")]
  verified: Option<bool>
}

impl ModelsDomain {
  pub fn new() -> ModelsDomain {
    ModelsDomain {
      created: None,
      dkim: None,
      dkim_config: None,
      dkim_verified: None,
      id: None,
      name: None,
      return_path: None,
      return_path_verified: None,
      track: None,
      track_verified: None,
      verified: None
    }
  }

  pub fn set_created(&mut self, created: i64) {
    self.created = Some(created);
  }

  pub fn with_created(mut self, created: i64) -> ModelsDomain {
    self.created = Some(created);
    self
  }

  pub fn created(&self) -> Option<&i64> {
    self.created.as_ref()
  }

  pub fn reset_created(&mut self) {
    self.created = None;
  }

  pub fn set_dkim(&mut self, dkim: ::models::ModelsDnsRecord) {
    self.dkim = Some(dkim);
  }

  pub fn with_dkim(mut self, dkim: ::models::ModelsDnsRecord) -> ModelsDomain {
    self.dkim = Some(dkim);
    self
  }

  pub fn dkim(&self) -> Option<&::models::ModelsDnsRecord> {
    self.dkim.as_ref()
  }

  pub fn reset_dkim(&mut self) {
    self.dkim = None;
  }

  pub fn set_dkim_config(&mut self, dkim_config: String) {
    self.dkim_config = Some(dkim_config);
  }

  pub fn with_dkim_config(mut self, dkim_config: String) -> ModelsDomain {
    self.dkim_config = Some(dkim_config);
    self
  }

  pub fn dkim_config(&self) -> Option<&String> {
    self.dkim_config.as_ref()
  }

  pub fn reset_dkim_config(&mut self) {
    self.dkim_config = None;
  }

  pub fn set_dkim_verified(&mut self, dkim_verified: bool) {
    self.dkim_verified = Some(dkim_verified);
  }

  pub fn with_dkim_verified(mut self, dkim_verified: bool) -> ModelsDomain {
    self.dkim_verified = Some(dkim_verified);
    self
  }

  pub fn dkim_verified(&self) -> Option<&bool> {
    self.dkim_verified.as_ref()
  }

  pub fn reset_dkim_verified(&mut self) {
    self.dkim_verified = None;
  }

  pub fn set_id(&mut self, id: i64) {
    self.id = Some(id);
  }

  pub fn with_id(mut self, id: i64) -> ModelsDomain {
    self.id = Some(id);
    self
  }

  pub fn id(&self) -> Option<&i64> {
    self.id.as_ref()
  }

  pub fn reset_id(&mut self) {
    self.id = None;
  }

  pub fn set_name(&mut self, name: String) {
    self.name = Some(name);
  }

  pub fn with_name(mut self, name: String) -> ModelsDomain {
    self.name = Some(name);
    self
  }

  pub fn name(&self) -> Option<&String> {
    self.name.as_ref()
  }

  pub fn reset_name(&mut self) {
    self.name = None;
  }

  pub fn set_return_path(&mut self, return_path: ::models::ModelsDnsRecord) {
    self.return_path = Some(return_path);
  }

  pub fn with_return_path(mut self, return_path: ::models::ModelsDnsRecord) -> ModelsDomain {
    self.return_path = Some(return_path);
    self
  }

  pub fn return_path(&self) -> Option<&::models::ModelsDnsRecord> {
    self.return_path.as_ref()
  }

  pub fn reset_return_path(&mut self) {
    self.return_path = None;
  }

  pub fn set_return_path_verified(&mut self, return_path_verified: bool) {
    self.return_path_verified = Some(return_path_verified);
  }

  pub fn with_return_path_verified(mut self, return_path_verified: bool) -> ModelsDomain {
    self.return_path_verified = Some(return_path_verified);
    self
  }

  pub fn return_path_verified(&self) -> Option<&bool> {
    self.return_path_verified.as_ref()
  }

  pub fn reset_return_path_verified(&mut self) {
    self.return_path_verified = None;
  }

  pub fn set_track(&mut self, track: ::models::ModelsDnsRecord) {
    self.track = Some(track);
  }

  pub fn with_track(mut self, track: ::models::ModelsDnsRecord) -> ModelsDomain {
    self.track = Some(track);
    self
  }

  pub fn track(&self) -> Option<&::models::ModelsDnsRecord> {
    self.track.as_ref()
  }

  pub fn reset_track(&mut self) {
    self.track = None;
  }

  pub fn set_track_verified(&mut self, track_verified: bool) {
    self.track_verified = Some(track_verified);
  }

  pub fn with_track_verified(mut self, track_verified: bool) -> ModelsDomain {
    self.track_verified = Some(track_verified);
    self
  }

  pub fn track_verified(&self) -> Option<&bool> {
    self.track_verified.as_ref()
  }

  pub fn reset_track_verified(&mut self) {
    self.track_verified = None;
  }

  pub fn set_verified(&mut self, verified: bool) {
    self.verified = Some(verified);
  }

  pub fn with_verified(mut self, verified: bool) -> ModelsDomain {
    self.verified = Some(verified);
    self
  }

  pub fn verified(&self) -> Option<&bool> {
    self.verified.as_ref()
  }

  pub fn reset_verified(&mut self) {
    self.verified = None;
  }

}



