/* 
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ModelsRdSuppression {
  #[serde(rename = "suppressions")]
  suppressions: Option<Vec<::models::ModelsSuppressionEmail>>
}

impl ModelsRdSuppression {
  pub fn new() -> ModelsRdSuppression {
    ModelsRdSuppression {
      suppressions: None
    }
  }

  pub fn set_suppressions(&mut self, suppressions: Vec<::models::ModelsSuppressionEmail>) {
    self.suppressions = Some(suppressions);
  }

  pub fn with_suppressions(mut self, suppressions: Vec<::models::ModelsSuppressionEmail>) -> ModelsRdSuppression {
    self.suppressions = Some(suppressions);
    self
  }

  pub fn suppressions(&self) -> Option<&Vec<::models::ModelsSuppressionEmail>> {
    self.suppressions.as_ref()
  }

  pub fn reset_suppressions(&mut self) {
    self.suppressions = None;
  }

}



