/* 
 * SendPost API
 *
 * SendPost API to send transactional emails reliably
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct UaparserOs {
  #[serde(rename = "Family")]
  family: Option<String>,
  #[serde(rename = "Major")]
  major: Option<String>,
  #[serde(rename = "Minor")]
  minor: Option<String>,
  #[serde(rename = "Patch")]
  patch: Option<String>,
  #[serde(rename = "PatchMinor")]
  patch_minor: Option<String>
}

impl UaparserOs {
  pub fn new() -> UaparserOs {
    UaparserOs {
      family: None,
      major: None,
      minor: None,
      patch: None,
      patch_minor: None
    }
  }

  pub fn set_family(&mut self, family: String) {
    self.family = Some(family);
  }

  pub fn with_family(mut self, family: String) -> UaparserOs {
    self.family = Some(family);
    self
  }

  pub fn family(&self) -> Option<&String> {
    self.family.as_ref()
  }

  pub fn reset_family(&mut self) {
    self.family = None;
  }

  pub fn set_major(&mut self, major: String) {
    self.major = Some(major);
  }

  pub fn with_major(mut self, major: String) -> UaparserOs {
    self.major = Some(major);
    self
  }

  pub fn major(&self) -> Option<&String> {
    self.major.as_ref()
  }

  pub fn reset_major(&mut self) {
    self.major = None;
  }

  pub fn set_minor(&mut self, minor: String) {
    self.minor = Some(minor);
  }

  pub fn with_minor(mut self, minor: String) -> UaparserOs {
    self.minor = Some(minor);
    self
  }

  pub fn minor(&self) -> Option<&String> {
    self.minor.as_ref()
  }

  pub fn reset_minor(&mut self) {
    self.minor = None;
  }

  pub fn set_patch(&mut self, patch: String) {
    self.patch = Some(patch);
  }

  pub fn with_patch(mut self, patch: String) -> UaparserOs {
    self.patch = Some(patch);
    self
  }

  pub fn patch(&self) -> Option<&String> {
    self.patch.as_ref()
  }

  pub fn reset_patch(&mut self) {
    self.patch = None;
  }

  pub fn set_patch_minor(&mut self, patch_minor: String) {
    self.patch_minor = Some(patch_minor);
  }

  pub fn with_patch_minor(mut self, patch_minor: String) -> UaparserOs {
    self.patch_minor = Some(patch_minor);
    self
  }

  pub fn patch_minor(&self) -> Option<&String> {
    self.patch_minor.as_ref()
  }

  pub fn reset_patch_minor(&mut self) {
    self.patch_minor = None;
  }

}



